---
groups:
  - name: bosh-setup-template
    jobs:
      - minimum-parameters
      - auto-deploy-bosh
  - name: deploy-cf-e2e
    jobs:
      - single
      - multiple
      - enterprise
  - name: advanced
    jobs:
      - diego

jobs:
- name: minimum-parameters
  serial: true
  plan:
  - aggregate:
    - {trigger: false, get: bosh-setup-template, resource: bosh-setup-template}

  - task: deploy
    file: bosh-setup-template/bosh-setup/ci/tasks/deploy-template-minimum.yml
    config:
      params:
        AZURE_CLIENT_ID:                {{azure_client_id}}
        AZURE_CLIENT_SECRET:            {{azure_client_secret}}
        AZURE_TENANT_ID:                {{azure_tenant_id}}
        AZURE_REGION_NAME:              {{azure_region_name}}
        SSH_KEY_DATA:                   {{ssh_key_data}}

- name: auto-deploy-bosh
  serial: true
  plan:
  - aggregate:
    - {trigger: false, get: bosh-setup-template, resource: bosh-setup-template}

  - task: deploy
    file: bosh-setup-template/bosh-setup/ci/tasks/deploy-template-autoDeployBosh.yml
    config:
      params:
        AZURE_CLIENT_ID:                {{azure_client_id}}
        AZURE_CLIENT_SECRET:            {{azure_client_secret}}
        AZURE_TENANT_ID:                {{azure_tenant_id}}
        AZURE_REGION_NAME:              {{azure_region_name}}
        SSH_KEY_DATA:                   {{ssh_key_data}}

- name: single
  serial: true
  plan:
  - aggregate:
    - {trigger: false, get: bosh-setup-template, resource: bosh-setup-template}

  - task: deploy
    file: bosh-setup-template/bosh-setup/ci/tasks/deploy-single-vm-cf.yml
    config:
      params:
        AZURE_CLIENT_ID:                {{azure_client_id}}
        AZURE_CLIENT_SECRET:            {{azure_client_secret}}
        AZURE_TENANT_ID:                {{azure_tenant_id}}
        AZURE_REGION_NAME:              {{azure_region_name}}
        SSH_KEY_DATA:                   {{ssh_key_data}}

- name: multiple
  serial: true
  plan:
  - aggregate:
    - {trigger: false, get: bosh-setup-template, resource: bosh-setup-template}

  - task: deploy
    file: bosh-setup-template/bosh-setup/ci/tasks/deploy-multiple-vm-cf.yml
    config:
      params:
        AZURE_CLIENT_ID:                {{azure_client_id}}
        AZURE_CLIENT_SECRET:            {{azure_client_secret}}
        AZURE_TENANT_ID:                {{azure_tenant_id}}
        AZURE_REGION_NAME:              {{azure_region_name}}
        SSH_KEY_DATA:                   {{ssh_key_data}}

- name: enterprise
  serial: true
  plan:
  - aggregate:
    - {trigger: false, get: bosh-setup-template, resource: bosh-setup-template}

  - task: deploy
    file: bosh-setup-template/bosh-setup/ci/tasks/deploy-enterprise-cf.yml
    config:
      params:
        AZURE_CLIENT_ID:                {{azure_client_id}}
        AZURE_CLIENT_SECRET:            {{azure_client_secret}}
        AZURE_TENANT_ID:                {{azure_tenant_id}}
        AZURE_REGION_NAME:              {{azure_region_name}}
        SSH_KEY_DATA:                   {{ssh_key_data}}

- name: diego
  serial: true
  plan:
  - aggregate:
    - {trigger: false, get: bosh-setup-template, resource: bosh-setup-template}

  - task: deploy
    file: bosh-setup-template/bosh-setup/ci/tasks/deploy-diego.yml
    config:
      params:
        AZURE_CLIENT_ID:                {{azure_client_id}}
        AZURE_CLIENT_SECRET:            {{azure_client_secret}}
        AZURE_TENANT_ID:                {{azure_tenant_id}}
        AZURE_REGION_NAME:              {{azure_region_name}}
        SSH_KEY_DATA:                   {{ssh_key_data}}

resources:
- name: bosh-setup-template
  type: git
  source:
    uri: git@github.com:bingosummer/azure-quickstart-templates.git
    branch: develop
    private_key: {{github_deployment_key__bosh-setup-template}}
