---
groups:
  - name: deploy-cf-e2e
    jobs:
      - basic

jobs:
- name: basic
  serial: true
  plan:
  - aggregate:
    - {trigger: false, get: bosh-setup-template, resource: bosh-setup-template}

  - task: deploy-bosh
    file: bosh-setup-template/bosh-setup/ci/tasks/deploy-bosh.yml
    config:
      params:
        AZURE_CLIENT_ID:                {{azure_client_id}}
        AZURE_CLIENT_SECRET:            {{azure_client_secret}}
        AZURE_TENANT_ID:                {{azure_tenant_id}}
        AZURE_GROUP_NAME:               {{azure_group_name}}
        AZURE_REGION_NAME:              {{azure_region_name}}
        SSH_KEY_DATA:                   {{ssh_key_data}}

  - task: deploy-single-vm-cf
    file: bosh-setup-template/bosh-setup/ci/tasks/deploy-single-vm-cf.yml
    config:
      params:
        AZURE_CLIENT_ID:                {{azure_client_id}}
        AZURE_CLIENT_SECRET:            {{azure_client_secret}}
        AZURE_TENANT_ID:                {{azure_tenant_id}}
        AZURE_GROUP_NAME:               {{azure_group_name}}

  - task: cleanup
    file: bosh-setup-template/bosh-setup/ci/tasks/cleanup.yml
    config:
      params:
        AZURE_CLIENT_ID:                {{azure_client_id}}
        AZURE_CLIENT_SECRET:            {{azure_client_secret}}
        AZURE_TENANT_ID:                {{azure_tenant_id}}
        AZURE_GROUP_NAME:               {{azure_group_name}}
        

resources:
- name: bosh-setup-template
  type: git
  source:
    uri: git@github.com:bingosummer/azure-quickstart-templates.git
    branch: develop
    private_key: {{github_deployment_key__bosh-setup-template}}
