---
platform: linux
image: docker:///boshcpi/azure-cpi-release
inputs:
  - name: bosh-setup-template
run:
  path: bosh-setup-template/bosh-setup/ci/tasks/cleanup.sh
params:
    AZURE_CLIENT_ID:               replace-me
    AZURE_CLIENT_SECRET:           replace-me
    AZURE_TENANT_ID:               replace-me
    AZURE_GROUP_NAME:              replace-me
