- type: replace
  path: /releases/name=cf-mysql/url
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/cf-mysql-36.15.0-ubuntu-xenial-97.18-20180925-180805-323206939.tgz
- type: replace
  path: /releases/name=cf-mysql/version
  value: 36.15.0
- type: replace
  path: /releases/name=cf-mysql/sha1
  value: 9101651c0e51e82399715912fbc42bcbcfa23eca
- type: replace
  path: /releases/name=capi/url
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/capi-1.69.0-ubuntu-xenial-97.18-20180925-174321-043477082.tgz
- type: replace
  path: /releases/name=capi/version
  value: 1.69.0
- type: replace
  path: /releases/name=capi/sha1
  value: 21b21977095112135749ae6687861c1ab2b9d9de
- type: replace
  path: /releases/name=binary-buildpack/url
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/binary-buildpack-1.0.25-ubuntu-xenial-97.18-20180925-173733-854069576.tgz
- type: replace
  path: /releases/name=binary-buildpack/version
  value: 1.0.25
- type: replace
  path: /releases/name=binary-buildpack/sha1
  value: b9d0d4dafac36211ce4c2dad7d589b4127ecffd9
- type: replace
  path: /releases/name=cf-networking/url
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/cf-networking-2.16.0-ubuntu-xenial-97.18-20180925-174029-270284057.tgz
- type: replace
  path: /releases/name=cf-networking/version
  value: 2.16.0
- type: replace
  path: /releases/name=cf-networking/sha1
  value: 9909141908c3a94fe943f745beed452dfc4e67ba
- type: replace
  path: /releases/name=uaa/url
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/uaa-61.0-ubuntu-xenial-97.18-20180925-174003-087379214.tgz
- type: replace
  path: /releases/name=uaa/version
  value: "61.0"
- type: replace
  path: /releases/name=uaa/sha1
  value: 87648a056a4eb8b19568700f9a9e8946469bca59
- type: replace
  path: /releases/name=nats/url
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/nats-26-ubuntu-xenial-97.18-20180925-173907-106780018.tgz
- type: replace
  path: /releases/name=nats/version
  value: "26"
- type: replace
  path: /releases/name=nats/sha1
  value: bce7f4925156f6e10bc69a73f0bf812432fa3685
- type: replace
  path: /releases/name=diego/url
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/diego-2.18.0-ubuntu-xenial-97.18-20180925-174202-643118891.tgz
- type: replace
  path: /releases/name=diego/version
  value: 2.18.0
- type: replace
  path: /releases/name=diego/sha1
  value: 2b305a39573e500d660e89df1f4f852974ba88b2
- type: replace
  path: /releases/name=routing/url
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/routing-0.182.0-ubuntu-xenial-97.18-20180925-174104-027167581.tgz
- type: replace
  path: /releases/name=routing/version
  value: 0.182.0
- type: replace
  path: /releases/name=routing/sha1
  value: f0b164c62af9c657ad0b87e1b240285cc8c6d761
- type: replace
  path: /releases/name=cflinuxfs2/url
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/cflinuxfs2-1.238.0-ubuntu-xenial-97.18-20180925-173756-355381223.tgz
- type: replace
  path: /releases/name=cflinuxfs2/version
  value: 1.238.0
- type: replace
  path: /releases/name=cflinuxfs2/sha1
  value: fdc368075dbe7e82891d7f9289c65b87cb12da7d
- type: replace
  path: /releases/name=garden-runc/url
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/garden-runc-1.16.4-ubuntu-xenial-97.18-20180925-174338-28099955.tgz
- type: replace
  path: /releases/name=garden-runc/version
  value: 1.16.4
- type: replace
  path: /releases/name=garden-runc/sha1
  value: 89216d58fe8eb03212847ea8da6263591d442a67
- type: replace
  path: /releases/name=loggregator/url
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/loggregator-103.2-ubuntu-xenial-97.18-20180925-174021-29342313.tgz
- type: replace
  path: /releases/name=loggregator/version
  value: "103.2"
- type: replace
  path: /releases/name=loggregator/sha1
  value: dcf77483c17e54a4c0805895cc929ef796964453
- type: replace
  path: /releases/name=go-buildpack/url
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/go-buildpack-1.8.26-ubuntu-xenial-97.18-20180925-173705-150946666.tgz
- type: replace
  path: /releases/name=go-buildpack/version
  value: 1.8.26
- type: replace
  path: /releases/name=go-buildpack/sha1
  value: c3e0e51c1884c0e53f22189e4a3a9a32dc1d1ccf
- type: replace
  path: /releases/name=php-buildpack/url
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/php-buildpack-4.3.59-ubuntu-xenial-97.18-20180925-173722-627511363.tgz
- type: replace
  path: /releases/name=php-buildpack/version
  value: 4.3.59
- type: replace
  path: /releases/name=php-buildpack/sha1
  value: 7e278bff6e55a659beb8564bfa4fdca56efc326c
- type: replace
  path: /releases/name=cf-smoke-tests/url
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/cf-smoke-tests-40.0.9-ubuntu-xenial-97.18-20180925-173742-569031667.tgz
- type: replace
  path: /releases/name=cf-smoke-tests/version
  value: 40.0.9
- type: replace
  path: /releases/name=cf-smoke-tests/sha1
  value: 68a4a9eaffac44533b0afe555f6612d7d11f4b2c
- type: replace
  path: /releases/name=java-buildpack/url
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/java-buildpack-4.15-ubuntu-xenial-97.18-20180925-173722-613261036.tgz
- type: replace
  path: /releases/name=java-buildpack/version
  value: "4.15"
- type: replace
  path: /releases/name=java-buildpack/sha1
  value: b99def2ea9372f64e0d971854683ee8a8df41d88
- type: replace
  path: /releases/name=ruby-buildpack/url
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/ruby-buildpack-1.7.22-ubuntu-xenial-97.18-20180925-173733-854198591.tgz
- type: replace
  path: /releases/name=ruby-buildpack/version
  value: 1.7.22
- type: replace
  path: /releases/name=ruby-buildpack/sha1
  value: 41b14d7364a143912e7b7f3d8ba8c5332a6dd489
- type: replace
  path: /releases/name=statsd-injector/url
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/statsd-injector-1.4.0-ubuntu-xenial-97.18-20180926-162542-619498236.tgz
- type: replace
  path: /releases/name=statsd-injector/version
  value: 1.4.0
- type: replace
  path: /releases/name=statsd-injector/sha1
  value: a29936b19fbe8b95bf7a50ddbc3e86b7d84d46d9
- type: replace
  path: /releases/name=nodejs-buildpack/url
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/nodejs-buildpack-1.6.30-ubuntu-xenial-97.18-20180925-173733-854030797.tgz
- type: replace
  path: /releases/name=nodejs-buildpack/version
  value: 1.6.30
- type: replace
  path: /releases/name=nodejs-buildpack/sha1
  value: 2a4904eada3d73f66641c7594d2ee9b0f7148e0a
- type: replace
  path: /releases/name=python-buildpack/url
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/python-buildpack-1.6.20-ubuntu-xenial-97.18-20180925-173722-605340989.tgz
- type: replace
  path: /releases/name=python-buildpack/version
  value: 1.6.20
- type: replace
  path: /releases/name=python-buildpack/sha1
  value: 64fa61e4a710fa2ac2319ad2d4c0de7191081f87
- type: replace
  path: /releases/name=staticfile-buildpack/url
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/staticfile-buildpack-1.4.31-ubuntu-xenial-97.18-20180925-173722-605776889.tgz
- type: replace
  path: /releases/name=staticfile-buildpack/version
  value: 1.4.31
- type: replace
  path: /releases/name=staticfile-buildpack/sha1
  value: 9f22c703a6ab47bdf969065061f733b2bb889bac
- type: replace
  path: /releases/name=dotnet-core-buildpack/url
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/dotnet-core-buildpack-2.1.4-ubuntu-xenial-97.18-20180925-173712-605823301.tgz
- type: replace
  path: /releases/name=dotnet-core-buildpack/version
  value: 2.1.4
- type: replace
  path: /releases/name=dotnet-core-buildpack/sha1
  value: 84e267d9bcbfbc033f8a755dc240129ad815c7f3
- type: replace
  path: /releases/name=cf-syslog-drain/url
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/cf-syslog-drain-7.1-ubuntu-xenial-97.18-20180925-174049-533340332.tgz
- type: replace
  path: /releases/name=cf-syslog-drain/version
  value: "7.1"
- type: replace
  path: /releases/name=cf-syslog-drain/sha1
  value: 0af7b06615be97e1b440f7bd0d336c40ba953a10
- type: replace
  path: /releases/name=bpm/url
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/bpm-0.12.3-ubuntu-xenial-97.18-20180925-174002-592029761.tgz
- type: replace
  path: /releases/name=bpm/version
  value: 0.12.3
- type: replace
  path: /releases/name=bpm/sha1
  value: 6a1277c5d051ad35560c22449fd56fd4937be199
- type: replace
  path: /releases/name=loggregator-agent/url
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/loggregator-agent-2.3-ubuntu-xenial-97.18-20180926-195016-345522063.tgz
- type: replace
  path: /releases/name=loggregator-agent/version
  value: "2.3"
- type: replace
  path: /releases/name=loggregator-agent/sha1
  value: 347dd07e0e314543a3732016dde43a3522423240
- type: replace
  path: /releases/name=silk/url
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/silk-2.16.0-ubuntu-xenial-97.18-20180925-174021-29357326.tgz
- type: replace
  path: /releases/name=silk/version
  value: 2.16.0
- type: replace
  path: /releases/name=silk/sha1
  value: 370cdedd9cfb506114118662c24624ba42e96c8b
- type: replace
  path: /releases/name=bpm/stemcell?
  value:
    os: ubuntu-xenial
    version: "97.18"
- type: replace
  path: /releases/name=capi/stemcell?
  value:
    os: ubuntu-xenial
    version: "97.18"
- type: replace
  path: /releases/name=cf-mysql/stemcell?
  value:
    os: ubuntu-xenial
    version: "97.18"
- type: replace
  path: /releases/name=binary-buildpack/stemcell?
  value:
    os: ubuntu-xenial
    version: "97.18"
- type: replace
  path: /releases/name=cf-networking/stemcell?
  value:
    os: ubuntu-xenial
    version: "97.18"
- type: replace
  path: /releases/name=cf-smoke-tests/stemcell?
  value:
    os: ubuntu-xenial
    version: "97.18"
- type: replace
  path: /releases/name=cf-syslog-drain/stemcell?
  value:
    os: ubuntu-xenial
    version: "97.18"
- type: replace
  path: /releases/name=cflinuxfs2/stemcell?
  value:
    os: ubuntu-xenial
    version: "97.18"
- type: replace
  path: /releases/name=diego/stemcell?
  value:
    os: ubuntu-xenial
    version: "97.18"
- type: replace
  path: /releases/name=dotnet-core-buildpack/stemcell?
  value:
    os: ubuntu-xenial
    version: "97.18"
- type: replace
  path: /releases/name=garden-runc/stemcell?
  value:
    os: ubuntu-xenial
    version: "97.18"
- type: replace
  path: /releases/name=go-buildpack/stemcell?
  value:
    os: ubuntu-xenial
    version: "97.18"
- type: replace
  path: /releases/name=java-buildpack/stemcell?
  value:
    os: ubuntu-xenial
    version: "97.18"
- type: replace
  path: /releases/name=loggregator/stemcell?
  value:
    os: ubuntu-xenial
    version: "97.18"
- type: replace
  path: /releases/name=loggregator-agent/stemcell?
  value:
    os: ubuntu-xenial
    version: "97.18"
- type: replace
  path: /releases/name=nats/stemcell?
  value:
    os: ubuntu-xenial
    version: "97.18"
- type: replace
  path: /releases/name=nodejs-buildpack/stemcell?
  value:
    os: ubuntu-xenial
    version: "97.18"
- type: replace
  path: /releases/name=php-buildpack/stemcell?
  value:
    os: ubuntu-xenial
    version: "97.18"
- type: replace
  path: /releases/name=python-buildpack/stemcell?
  value:
    os: ubuntu-xenial
    version: "97.18"
- type: replace
  path: /releases/name=routing/stemcell?
  value:
    os: ubuntu-xenial
    version: "97.18"
- type: replace
  path: /releases/name=ruby-buildpack/stemcell?
  value:
    os: ubuntu-xenial
    version: "97.18"
- type: replace
  path: /releases/name=cf-mysql/stemcell?
  value:
    os: ubuntu-xenial
    version: "97.18"
- type: replace
  path: /releases/name=silk/stemcell?
  value:
    os: ubuntu-xenial
    version: "97.18"
- type: replace
  path: /releases/name=staticfile-buildpack/stemcell?
  value:
    os: ubuntu-xenial
    version: "97.18"
- type: replace
  path: /releases/name=statsd-injector/stemcell?
  value:
    os: ubuntu-xenial
    version: "97.18"
- type: replace
  path: /releases/name=uaa/stemcell?
  value:
    os: ubuntu-xenial
    version: "97.18"
- type: replace
  path: /releases/name=bosh-dns-aliases/url
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/bosh-dns-aliases-0.0.3-ubuntu-xenial-97.18-20180925-173125-866259283.tgz
- type: replace
  path: /releases/name=bosh-dns-aliases/version
  value: 0.0.3
- type: replace
  path: /releases/name=bosh-dns-aliases/sha1
  value: 65da4a04e73963cb314cbf88bda239ef27e9e0d1
- type: replace
  path: /releases/name=log-cache/url
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/log-cache-1.4.6-ubuntu-xenial-97.18-20180925-174049-660925325.tgz
- type: replace
  path: /releases/name=log-cache/version
  value: 1.4.6
- type: replace
  path: /releases/name=log-cache/sha1
  value: 4844d2e5732413589ee2fc19fbc91924db89af75
- type: replace
  path: /releases/name=credhub/url
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/credhub-2.0.2-ubuntu-xenial-97.18-20180925-173939-152956631.tgz
- type: replace
  path: /releases/name=credhub/sha1
  value: 38256eb9f9ea857f7a3ca724b7b3bdbba879ab69
- type: replace
  path: /releases/name=credhub/version
  value: 2.0.2
- type: replace
  path: /releases/name=credhub/stemcell?
  value:
    os: ubuntu-xenial
    version: "97.18"
- type: replace
  path: /releases/name=cf-cli/url
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/cf-cli-1.8.0-ubuntu-xenial-97.18-20180925-173722-627491828.tgz
- type: replace
  path: /releases/name=cf-cli/sha1
  value: d8753a7c168c131b240d3d70a46d7d4166a29746
- type: replace
  path: /releases/name=cf-cli/version
  value: 1.8.0
- type: replace
  path: /releases/name=cf-cli/stemcell?
  value:
    os: ubuntu-xenial
    version: "97.18"
- type: replace
  path: /releases/name=log-cache/stemcell?
  value:
    os: ubuntu-xenial
    version: "97.18"
- type: replace
  path: /releases/name=bosh-dns-aliases/stemcell?
  value:
    os: ubuntu-xenial
    version: "97.18"
